### ISSUE TITLE
Wrong Typos on Lab

### ISSUE THREAD

**Issue by cmsp94** [microsoft/EPPC23-ALM#15]
Hey guys,

Great workshop! Just a small list of missing typos on the lab:
- Lab 03, there is a typo on the Copy highlight "Navigate" PowerFx formula, missing the end ).
<img width="800" alt="image" src="https://github.com/microsoft/EPPC23-ALM/assets/137157606/5d4698b2-c474-4d75-8467-9321d245e1e9">
- Lab 04, on the stage of Adding the Deploy to X stage, there is a typo on Point 5 that says New Development Step instead of the New Deployment Step.
<img width="820" alt="image" src="https://github.com/microsoft/EPPC23-ALM/assets/137157606/87294cf7-8955-4204-ad2a-7036fe14f093">
- Lab 04, while testing the app after the deploy, there is a mention regarding the 2 buttons in the app, however it is now 3 because of the addition of the Testing button (in a prior lab)
<img width="786" alt="image" src="https://github.com/microsoft/EPPC23-ALM/assets/137157606/967efaa4-0585-458b-b799-bf18ce48750e">

**Comment by gomomohapi** [comment]
All issues have been fixed :)
